CREATE TABLE IF NOT EXISTS "User" (
	"id" INTEGER NOT NULL,
	"username" TEXT NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Pilot" (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL UNIQUE,
	"gold" INTEGER NOT NULL DEFAULT 0,
	"sponsor" INTEGER NOT NULL DEFAULT 0,
	"point" INTEGER NOT NULL DEFAULT 0,
	"championship_id" INTEGER,
	"team" INTEGER NOT NULL,
	"user_id" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("team") REFERENCES "Team"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("championship_id") REFERENCES "Championship "("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("user_id") REFERENCES "User"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Deck" (
	"id" INTEGER NOT NULL,
	"cards" TEXT,
	"id_prototype" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id_prototype") REFERENCES "Deck_prototype"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Championship " (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL UNIQUE,
	"pilots" TEXT,
	"deck" INTEGER,
	"date" DATETIME NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("deck") REFERENCES "Deck"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Team" (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Deck_prototype" (
	"id" INTEGER NOT NULL,
	"base_cards" TEXT,
	"name" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
