"""schema iniziale

Revision ID: 3201b138ce2e
Revises: 
Create Date: 2026-10-01 01:05:03.157302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3201b138ce2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_prototype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_cards', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('deck_prototype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_prototype_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='player', nullable=False),
    sa.CheckConstraint("role IN ('admin', 'player')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cards', sa.String(), nullable=True),
    sa.Column('id_prototype', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prototype'], ['deck_prototype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_id'), ['id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_id'), ['id'], unique=False)

    op.create_table('championship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('pool_deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pool_deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('championship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_championship_id'), ['id'], unique=False)

    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sponsor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('point', sa.Integer(), server_default='0', nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inventory_deck_id', sa.Integer(), nullable=False),
    sa.Column('game_deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['inventory_deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_deck_id'),
    sa.UniqueConstraint('inventory_deck_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pilot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pilot_id'), ['id'], unique=False)

    op.create_table('championship_pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('championship_id', 'pilot_id')
    )
    with op.batch_alter_table('championship_pilot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_championship_pilot_id'), ['id'], unique=False)

    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('championship_id', 'number')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_id'), ['id'], unique=False)

    op.create_table('race_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 12', name='ck_race_result_position'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'pilot_id'),
    sa.UniqueConstraint('race_id', 'position')
    )
    with op.batch_alter_table('race_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_result_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_result_id'))

    op.drop_table('race_result')
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_id'))

    op.drop_table('race')
    with op.batch_alter_table('championship_pilot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_championship_pilot_id'))

    op.drop_table('championship_pilot')
    with op.batch_alter_table('pilot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pilot_id'))

    op.drop_table('pilot')
    with op.batch_alter_table('championship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_championship_id'))

    op.drop_table('championship')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_id'))

    op.drop_table('team')
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_id'))

    op.drop_table('deck')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('deck_prototype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_prototype_id'))

    op.drop_table('deck_prototype')
    # ### end Alembic commands ###
